/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.app1;

import org.junit.Test;

public class AppTest {
  @Test public void appHasAGreeting() {
    ServerApp classUnderTest = new ServerApp();
    //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }
}
