/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.app1;

import org.junit.Test;

public class AppTest {
  @Test public void appHasAGreeting() {
    ClientApp classUnderTest = new ClientApp();
    //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }
}
